### ISSUE TITLE
DNS does not work with without explicit setting a dns nameserver

### ISSUE THREAD

**Issue by sesigl** [OneOfOne/pia-socks-proxy#1]
Hey,

first of all, thank your for this container. I am not that familiar with linux container and deep networking stuff like openvpn. Anyhow, I can tell you that this one works for me and it saves me a lot of time.

I would love to keep this docker image up2date, especially the region files :).

I used the container from https://github.com/qdm12/private-internet-access-docker before. But putting the container in the same namespace (`--network container:pia-container`) made it hard to switch it the pia proxy with ease. Socks5 makes it possible to just boot up a new container and switch the socks5 port of my browser.

I had some issues when I started your container to request real domains. I think dns did not work properly.

I had to add:

```
--dns 209.222.18.222 --dns 209.222.18.218
``` 

to my docker run command.

I did not research why this is the case but it fixed my issue. I think it would be cool if the hosts's dns server is used. The private-internet-access-docker container solves it also somehow :).

All the best

**Comment by OneOfOne** [comment]
Thanks for the kind words, I'll look into it, it's been a while.
